name: Branch Specific Workflow

on:
  push:
    branches: # Trigger on the specified branches
     # - main
      - develop
      #- feature/*
  pull_request:
    branches: # Trigger on pull requests targeting these branches
    #  - main
      - develop
     # - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build step for all branches
      - name: Build application
        run: |
          echo "Building the application"
          mvn clean package

  deploy-to-development:
    if: github.ref_name == 'develop' # Run only on the 'develop' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Development Server
        run: |
          echo "Deploying to the Development Server"
          scp -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no target/*.war ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/opt/tomcat/webapps/
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} <<EOF
          sudo /opt/tomcat/bin/shutdown.sh
          sudo /opt/tomcat/bin/startup.sh
          EOF

  deploy-to-production:
    if: github.ref_name == 'main' # Run only on the 'main' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: |
          echo "Deploying to the Production Server"
          scp -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no target/*.war ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/opt/tomcat/webapps/
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} <<EOF
          sudo /opt/tomcat/bin/shutdown.sh
          sudo /opt/tomcat/bin/startup.sh
          EOF

  build-feature-branch:
    if: startsWith(github.ref_name, 'feature/') # Run for branches starting with 'feature/'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build feature branch
        run: |
          echo "Building artifact for feature branch"
          mvn clean package
          echo "Build completed. Artifact located in the target directory."
